version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api:
    build:
      dockerfile: Dockerfile.server
    env_file:
      - ./.env

    ports:
      - 3000:3000
    depends_on:
      - postgres
